---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: sjoerdos
description: Sjoerd's Silverblue image, based on silverblue-nvidia image from ublue-os.
base-image: ghcr.io/ublue-os/silverblue-nvidia
image-version: latest

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

  - type: rpm-ostree
    repos:
      - https://copr.fedorainfracloud.org/coprs/bigjapka/VeraCrypt/repo/fedora-42/bigjapka-VeraCrypt-fedora-42.repo  
    install:
      - docker
      - veracrypt
      - binutils
      - gdb
    remove:
      - firefox
      - firefox-langpacks

  - from-file: default-flatpaks.yml

  - type: gnome-extensions
    install:
      - Caffeine
      - Quick Close in Overview
      - Alphabetical App Grid

  - type: os-release
    properties:
      ID: sjoerdos
      NAME: SjoerdOS
      PRETTY_NAME: SjoerdOS

  - type: gschema-overrides

  - type: signing # this sets up the proper policy & signing files for signed images to work fully

  - type: initramfs
