---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: sjoerdos
# description will be included in the image's metadata
description: This is my personal OS image.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/silverblue-nvidia
image-version: latest # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

  - type: rpm-ostree
   # repos:
   #   - https://copr.fedorainfracloud.org/coprs/atim/starship/repo/fedora-%OS_VERSION%/atim-starship-fedora-%OS_VERSION%.repo
    install:
      - docker
    remove:
      # example: removing firefox (in favor of the flatpak)
      # "firefox" is the main package, "firefox-langpacks" is a dependency
      - firefox
      - firefox-langpacks # also remove firefox dependency (not required for all packages, this is a special case)

type: default-flatpaks
configurations:
  - install:
      - org.mozilla.firefox
      - org.gnome.Loupe
      - org.gnome.Builder
      - org.fedoraproject.Sdk.Extension.texlive
      - org.texstudio.TeXstudio
      - se.sjoerd.Graphs
      - com.spotify.Client
      - com.valvesoftware.Steam
      - org.libreoffice.LibreOffice
      - org.gnome.Boxes
      - org.gimp.GIMP
      - org.ghidra_sre.Ghidra
      - app.zen_browser.zen
      - org.sqlitebrowser.sqlitebrowser
      - com.github.skylot.jadx
      - com.github.tchx84.Flatseal
      - page.tesk.Refine
    user: {} # Also add Flathub user repo, but no user packages

  - type: signing # this sets up the proper policy & signing files for signed images to work fully

